# BOO!! 
title: BOO!!
header-img: img/home-bg.jpg
email: kunfaz@yahoo.co.id
copyright_name: kunfaz 2016
description: "Welcome To BOO!! Feel Free and Enjoy!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "mrboo.github.io"
twitter_username: koenfaz
github_username:  kunfaz
facebook_username:  kungpas
email_username:  kunfaz@yahoo.co.id

# BOO!! BuildSettings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
